---
title: "R Notebook"
output: html_notebook
---

```{r}
get_rxys <- function(data) {
  d <- semi_join(rdat$gdata, data, by = c("V1" = "indiv"))
  rxy1 <- related::coancestry(d, quellergt=1, allele.freqs = rdat$freqs)$relatedness %>%
    as_tibble() %>%
    select(ind1.id, ind2.id, quellergt) %>%
    rename(ind1 = ind1.id, ind2 = ind2.id)
  rxy2 <- rxy1[, c(2,1,3)] %>%
    set_names(c("ind1", "ind2", "quellergt"))
  
  bind_rows(rxy1, rxy2)
}
```

```{r}
library(lubridate)

day_fish_WS_1 <- spawn_rows %>%
  mutate(spawn_date = mdy(spawn_date)) %>%
  filter(hatchery == "Warm_Springs") %>% 
  group_by(spawn_date) %>%
  nest() %>%
  arrange(spawn_date) %>%
  mutate(num_fish = map_int(data, nrow))

day_fish_CV_1 <- spawn_rows %>%
  mutate(spawn_date = mdy(spawn_date)) %>%
  filter(hatchery == "Coyote_Valley") %>% 
  group_by(spawn_date) %>%
  nest() %>%
  arrange(spawn_date) %>%
  mutate(num_fish = map_int(data, nrow))

day_fish_WS_1
day_fish_CV_1
```

```{r, eval=FALSE}
rxys_in_days_WS_1 <- day_fish_WS_1 %>%
  mutate(pairs = map(data, get_rxys))

rxys_in_days_CV_1 <- day_fish_CV_1 %>%
  mutate(pairs = map(data, get_rxys))
```

########

```{r}
rxys_in_days_WS_1 
rxys_in_days_CV_1
```

```{r}
#pairs has the rxy data, "quellergt"

rxys_in_days_WS_1 %>% 
  mutate(year = year(spawn_date)) %>% 
  ungroup %>% 
  count(year) %>% summarise(mean(n))
#15.5 spawn days per year at Warm Springs

rxys_in_days_CV_1 %>% 
  mutate(year = year(spawn_date)) %>% 
  ungroup %>% 
  count(year) %>% summarise(mean(n))
#14.1 spawn days per year at CV
```

```{r}
trythis <- function(x,y){
  a <- x %>%
    filter(year == y)
  
  b <- a$pairs %>% flatten
  mean_rxy <- a %>% 
    summarise(y, mean_qgt = mean(b$quellergt), num_rxys_in_mean = n() )
  
  print(mean_rxy)
}

one <- rxys_in_days_WS_1 %>% 
  mutate(year = year(spawn_date)) %>% 
  ungroup 
two <- rxys_in_days_CV_1 %>% 
  mutate(year = year(spawn_date)) %>% 
  ungroup 

years_WS <- as.list(seq(2007,2020, 1))
years_CV <- as.list(seq(2009,2020, 1))
  
  
stuff <- map_dfr(years_WS, ~trythis(one,.x)) %>% mutate(hatchery = "Warm_Springs")

stuff2 <-  map_dfr(years_CV, ~trythis(two,.x)) %>% mutate(hatchery = "Coyote_Valley")

all_stuff <- bind_rows(stuff, stuff2)

ggplot(all_stuff)+
  geom_point(aes(x = y, y =mean_qgt, color = hatchery))+
  geom_line(aes(x = y, y = mean_qgt, color = hatchery))+
  scale_color_brewer(palette = "Dark2")+
  scale_x_continuous(breaks=seq(2007,2020, 1))+
  #ylim(-0.0035, 0)+
  labs(title ="Annual mean relatedness of individuals spawned on the same day", y = "Mean relatedness among individuals")+
  theme_classic()

#write_rds(all_stuff, "annual_relatedness_by_spawn_day.rds")
  
```



Trying to look at relatednes of pairs and number of offspring per pair

```{r}
trio_stuff <- read_csv("/Users/annebeulke/Documents/Russian-River-R/Russian-River/RR_2007-2020_pedigree_ages_lengths.csv")
trio_stuff
```


```{r}
rxys_in_days_WS_1$data 
rxys_in_days_CV_1

extract_observed_rxy <- function(tdf, rxyp) {
  left_join(tdf, rxyp, by = c("pa" = "ind1", "ma" = "ind2"))
}

trio_stuff

rxy_results_WS <- interm1_WS %>%
  mutate(obs_rxy = map2(.x = trios, .y = rxy_pairs, .f = extract_observed_rxy))
rxy_results_CV <- interm1_CV %>%
  mutate(obs_rxy = map2(.x = trios, .y = rxy_pairs, .f = extract_observed_rxy)) 
  
rxy_results_CV
rxy_results_WS

library(tidyverse)
offspring_nums <- read_csv("/Users/annebeulke/Documents/Russian-River-R/Russian-River/RR_offspring_num_per_pair.csv") %>% separate(., id, sep = ":", into = c("pa", "ma")) %>% select(-type)
offspring_nums
```
```{r}


trythis2 <- function(rxy,offsp){
  a <- rxy %>%
    unnest(obs_rxy)

  b <- inner_join(a, offsp, by = c("pa", "ma"))
  
  print(b)
}


  
  
cv_qgt <- trythis2(rxy_results_CV, offspring_nums) %>% mutate(pair = str_c(pa, ma, sep = "_"))
ws_qgt <- trythis2(rxy_results_WS, offspring_nums) %>% mutate(pair = str_c(pa, ma, sep = "_"))
```

```{r}
ws1 <- ws_qgt %>% 
  group_by(pair) %>% 
  filter(n > 1) %>% 
  slice(1)

ws2 <- ws_qgt %>% 
  group_by(pair) %>% 
  filter(n <= 1) 

ws3 <- bind_rows(ws1,ws2)

cv1 <- cv_qgt %>% 
  group_by(pair) %>% 
  filter(n > 1) %>% 
  slice(1)

cv2 <- cv_qgt %>% 
  group_by(pair) %>% 
  filter(n <= 1) 

cv3 <- bind_rows(cv1,cv2)
```

```{r}

ggplot(data = ws3)+
  geom_hex(aes(x = quellergt, y = n))+
  labs(title = "Warm Springs", y ="Num Offspring per Pair", x = "rxy per pair")+
  scale_y_continuous(breaks = (seq(0, 30, 2)))+
  facet_wrap(~SpawnYear)

ggplot()+
  geom_hex(data = cv3, aes(x = quellergt, y = n))+
  labs(title = "Coyote Valley", y ="Num Offspring per Pair", x = "rxy per pair")+
  scale_y_continuous(breaks = (seq(0, 30, 1)))+
  facet_wrap(~SpawnYear)

ggplot()+
  geom_point(data = ws3, aes(x = quellergt, y = n))+
  labs(title = "Warm Springs", y ="Num Offspring per Pair", x = "rxy per pair")

ggplot()+
  geom_point(data = cv3, aes(x = quellergt, y = n))+
  labs(title = "Coyote Valley", y ="Num Offspring per Pair", x = "rxy per pair")

ggplot()+
  geom_count(data = ws3, aes(x = quellergt, y = n))+
  labs(title = "Warm Springs", y ="Num Offspring per Pair", x = "rxy per pair")

ggplot()+
  geom_count(data = cv3, aes(x = quellergt, y = n))+
  labs(title = "Coyote Valley", y ="Num Offspring per Pair", x = "rxy per pair")

ws3 %>% 
  ggplot()+
  geom_hex(aes(x = quellergt, y = n))+
  labs(title = "Warm Springs", y ="Num Offspring per Pair", x = "rxy per pair")+
  scale_y_continuous(breaks = (seq(0, 30, 2)))
  
ggplot()+
  geom_hex(data = cv3, aes(x = quellergt, y = n))+
  labs(title = "Coyote Valley", y ="Num Offspring per Pair", x = "rxy per pair")+
  scale_y_continuous(breaks = (seq(0, 30, 1)))


```

```{r}
cv_qgt %>% filter(n > 15)
ggplot()+
  geom_count(aes(x = quellergt, y = n))

ggplot()+
  geom_count(data = cv_qgt, aes(x = quellergt, y = n))
```




